mychat:
  mysql:
    host: dl
    port: 3306
    username: root
    password: 123456
    database: mychat
  redis:
    host: dl
    port: 6379
    password: 123456
    database: 10
  wx:
    app-id: wxee25fb4bc0926c6b
    aes-key: 1
    secret: df77b688b3a8785911558b8fe79ef32b
    token: mtlaa
    callback: http://mtlaaa.w1.luyouxia.net

rocketmq:
  name-server: 192.168.123.229:9876
  access-key: mychat
  secret-key: 12345678

oss:
  enabled: true
  type: minio
  endpoint: http://dl:9000
  access-key: OD2ChFMFsZYxysPh
  secret-key: ZOFiwimYzM1tAKIPZm3wERXryPhafp4c
  bucketName: mychat